# Generated by Django 5.2.9 on 2025-12-27 13:14

import django.db.models.deletion
import utils.storage.oss_storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0002_remove_song_cover_url_remove_song_file_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGCGenerationTask',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False, verbose_name='任务ID')),
                ('task_type', models.CharField(choices=[('lyric_image', '歌词配图'), ('comment_summary', '评论摘要')], db_index=True, max_length=50, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], db_index=True, default='pending', max_length=20, verbose_name='任务状态')),
                ('parameters', models.JSONField(default=dict, help_text='存储生成任务的参数，如风格、数量等', verbose_name='生成参数')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人员')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song', verbose_name='歌曲')),
            ],
            options={
                'verbose_name': 'AIGC生成任务',
                'verbose_name_plural': 'AIGC生成任务',
                'db_table': 'aigc_generation_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIGCContent',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False, verbose_name='内容ID')),
                ('content_type', models.CharField(help_text='image: 图片, text: 文字', max_length=20, verbose_name='内容类型')),
                ('content_url', models.URLField(help_text='OSS存储URL', max_length=500, verbose_name='内容URL')),
                ('content_file', models.ImageField(blank=True, help_text='图片文件（仅图片类型）', null=True, storage=utils.storage.oss_storage.OSSStorage(base_path='images'), upload_to='aigc/images/', verbose_name='内容文件')),
                ('content_text', models.TextField(blank=True, help_text='文字内容（仅文字类型）', null=True, verbose_name='内容文本')),
                ('metadata', models.JSONField(default=dict, help_text='存储内容的元数据，如尺寸、风格、字数等', verbose_name='元数据')),
                ('status', models.CharField(choices=[('pending_review', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('published', '已发布')], db_index=True, default='pending_review', max_length=20, verbose_name='内容状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_notes', models.TextField(blank=True, null=True, verbose_name='审核备注')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='发布时间')),
                ('usage_count', models.IntegerField(default=0, help_text='内容被使用的次数（前端展示次数）', verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_aigc_contents', to=settings.AUTH_USER_MODEL, verbose_name='审核人员')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aigc.aigcgenerationtask', verbose_name='生成任务')),
            ],
            options={
                'verbose_name': 'AIGC生成内容',
                'verbose_name_plural': 'AIGC生成内容',
                'db_table': 'aigc_contents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aigcgenerationtask',
            index=models.Index(fields=['song', 'task_type', 'status'], name='aigc_genera_song_id_1c93d3_idx'),
        ),
        migrations.AddIndex(
            model_name='aigcgenerationtask',
            index=models.Index(fields=['status', 'created_at'], name='aigc_genera_status_adc787_idx'),
        ),
        migrations.AddIndex(
            model_name='aigccontent',
            index=models.Index(fields=['task', 'status'], name='aigc_conten_task_id_3d67bf_idx'),
        ),
        migrations.AddIndex(
            model_name='aigccontent',
            index=models.Index(fields=['status', 'published_at'], name='aigc_conten_status_e9ecf9_idx'),
        ),
        migrations.AddIndex(
            model_name='aigccontent',
            index=models.Index(fields=['content_type', 'status'], name='aigc_conten_content_095af2_idx'),
        ),
    ]
