# Generated by Django 5.2.9 on 2025-12-27 14:35

import utils.storage.oss_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigccontent',
            name='content_video_file',
            field=models.FileField(blank=True, help_text='视频文件（仅视频类型）', null=True, storage=utils.storage.oss_storage.OSSStorage(base_path='videos'), upload_to='aigc/videos/', verbose_name='视频文件'),
        ),
        migrations.AlterField(
            model_name='aigccontent',
            name='content_file',
            field=models.FileField(blank=True, help_text='图片或视频文件', null=True, storage=utils.storage.oss_storage.OSSStorage(base_path='images'), upload_to='aigc/images/', verbose_name='内容文件'),
        ),
        migrations.AlterField(
            model_name='aigccontent',
            name='content_type',
            field=models.CharField(help_text='image: 图片, text: 文字, video: 视频', max_length=20, verbose_name='内容类型'),
        ),
        migrations.AlterField(
            model_name='aigcgenerationtask',
            name='task_type',
            field=models.CharField(choices=[('lyric_image', '歌词配图'), ('comment_summary', '评论摘要'), ('lyric_video', '歌词视频')], db_index=True, max_length=50, verbose_name='任务类型'),
        ),
    ]
