# Generated by Django 5.2.9 on 2025-12-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigc', '0002_aigccontent_content_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aigcgenerationtask',
            name='task_type',
            field=models.CharField(choices=[('lyric_image', '歌词配图'), ('comment_summary', '评论摘要'), ('lyric_video', '歌词视频'), ('text_to_video', '文生视频')], db_index=True, max_length=50, verbose_name='任务类型'),
        ),
    ]
