# Generated by Django 5.2.9 on 2025-12-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vip_type',
            field=models.CharField(blank=True, choices=[('monthly', '月度VIP'), ('quarterly', '季度VIP'), ('yearly', '年度VIP'), ('lifetime', '终身VIP'), ('trial', '体验VIP')], default='monthly', max_length=20, null=True, verbose_name='VIP类型'),
        ),
    ]
