# Generated by Django 5.2.9 on 2025-12-23 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False, verbose_name='歌曲ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='歌曲标题')),
                ('artist', models.CharField(db_index=True, max_length=100, verbose_name='艺术家')),
                ('album', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='专辑')),
                ('duration', models.IntegerField(verbose_name='时长(秒)')),
                ('file_url', models.URLField(max_length=500, verbose_name='文件URL')),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='封面URL')),
                ('lyrics', models.TextField(blank=True, null=True, verbose_name='歌词')),
                ('genre', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='音乐类型')),
                ('play_count', models.IntegerField(db_index=True, default=0, verbose_name='播放次数')),
                ('like_count', models.IntegerField(db_index=True, default=0, verbose_name='点赞数')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('bitrate', models.IntegerField(blank=True, null=True, verbose_name='比特率')),
                ('sample_rate', models.IntegerField(blank=True, null=True, verbose_name='采样率')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '歌曲',
                'verbose_name_plural': '歌曲',
                'db_table': 'songs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False, verbose_name='历史ID')),
                ('keyword', models.CharField(db_index=True, max_length=100, verbose_name='搜索关键词')),
                ('search_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='搜索类型')),
                ('result_count', models.IntegerField(blank=True, null=True, verbose_name='结果数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='搜索时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '搜索历史',
                'verbose_name_plural': '搜索历史',
                'db_table': 'search_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False, verbose_name='历史ID')),
                ('play_duration', models.IntegerField(blank=True, null=True, verbose_name='播放时长(秒)')),
                ('play_position', models.IntegerField(blank=True, null=True, verbose_name='播放位置(秒)')),
                ('device_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='设备信息')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='播放时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song', verbose_name='歌曲')),
            ],
            options={
                'verbose_name': '播放历史',
                'verbose_name_plural': '播放历史',
                'db_table': 'play_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
