# Generated by Django 5.2.9 on 2025-12-23 14:20

import utils.storage.oss_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='cover_url',
        ),
        migrations.RemoveField(
            model_name='song',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='song',
            name='file_url',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, help_text='支持MP3格式', null=True, storage=utils.storage.oss_storage.OSSStorage(base_path='audio'), upload_to='songs/', verbose_name='音频文件'),
        ),
        migrations.AddField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=utils.storage.oss_storage.OSSStorage(base_path='images'), upload_to='covers/', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, choices=[('pop', '流行'), ('rock', '摇滚'), ('jazz', '爵士'), ('classical', '古典'), ('electronic', '电子'), ('hiphop', '嘻哈'), ('r&b', 'R&B'), ('country', '乡村'), ('folk', '民谣'), ('blues', '蓝调'), ('metal', '金属'), ('reggae', '雷鬼'), ('latin', '拉丁'), ('world', '世界音乐'), ('other', '其他')], db_index=True, max_length=50, null=True, verbose_name='音乐类型'),
        ),
    ]
