# Generated by Django 5.2.9 on 2026-01-01 03:39

import utils.storage.oss_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_remove_song_cover_url_remove_song_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics_file',
            field=models.FileField(blank=True, help_text='支持LRC或SRT格式文件，上传后会自动解析并填充到歌词字段', null=True, storage=utils.storage.oss_storage.OSSStorage(base_path='files'), upload_to='lyrics/', verbose_name='歌词文件'),
        ),
    ]
