# Generated by Django 5.2.9 on 2026-01-01 19:07

import utils.storage.oss_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_song_lyrics_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='mv_video_file',
            field=models.FileField(blank=True, help_text='支持MP4格式，建议分辨率720p或1080p，文件大小不超过500MB', null=True, storage=utils.storage.oss_storage.OSSStorage(base_path='videos'), upload_to='mv/', verbose_name='MV视频文件'),
        ),
    ]
