# Generated by Django 5.2.9 on 2025-12-23 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('like_count', models.IntegerField(db_index=True, default=0, verbose_name='点赞数')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comment', verbose_name='父评论')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song', verbose_name='歌曲')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comments',
                'ordering': ['-like_count', '-created_at'],
            },
        ),
    ]
