# Generated by Django 5.2.9 on 2025-12-27 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCommentLike',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False, verbose_name='点赞ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.comment', verbose_name='评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户评论点赞',
                'verbose_name_plural': '用户评论点赞',
                'db_table': 'user_comment_likes',
                'indexes': [models.Index(fields=['user', 'comment'], name='user_commen_user_id_4343ed_idx'), models.Index(fields=['comment'], name='user_commen_comment_69c2a7_idx'), models.Index(fields=['created_at'], name='user_commen_created_b73913_idx')],
                'unique_together': {('user', 'comment')},
            },
        ),
    ]
